name: Jandex Release

run-name: Perform ${{github.event.inputs.tag || github.ref_name}} Release

on:
  push:
    tags:
    - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true

permissions:
  attestations: write
  id-token: write
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  perform-release:
    name: Perform Release
    uses: smallrye/.github/.github/workflows/perform-release.yml@main
    secrets: inherit
    with:
      version: ${{github.event.inputs.tag || github.ref_name}}

  github-pages:
    name: GitHub Pages
    needs: perform-release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: gh-pages

    - name: Set up Node.js 16
      uses: actions/setup-node@v4
      with:
        node-version: 16

    - name: Generate and push
      run: |
        node --version

        curl -s -L -o antora-playbook.yml https://github.com/smallrye/jandex/blob/main/doc/antora-playbook-prod.yml?raw=true

        npm install @antora/cli@3.0 @antora/site-generator-default@3.0
        npx antora generate antora-playbook.yml

        rm -rf node_modules docs package.json package-lock.json antora-playbook.yml
        mv -T build/site docs
        touch docs/.nojekyll

        git config --global user.name "SmallRye CI"
        git config --global user.email "smallrye@googlegroups.com"
        git status
        git add -A .
        git commit -m 'Generate documentation site'
        git push
