name: Jandex Release

run-name: Release ${{github.event.inputs.tag || github.ref_name}}

on:
  push:
    tags:
    - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true

permissions:
  attestations: write
  id-token: write
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  perform-release:
    name: Perform Release
    uses: smallrye/.github/.github/workflows/perform-release.yml@main
    secrets: inherit
    with:
      version: ${{github.event.inputs.tag || github.ref_name}}

  github-pages:
    name: GitHub Pages
    needs: perform-release
    uses: ./.github/workflows/pages.yml
